# Generated by Django 4.0.4 on 2022-05-30 00:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_topology', models.CharField(choices=[('V', 'Virtual'), ('P', 'Public')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Atendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salutation', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MISS', 'Miss.'), ('MS', 'Ms.')], max_length=4)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(db_index=True, max_length=32)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('events', models.ManyToManyField(db_index=True, to='core_app.event')),
            ],
        ),
    ]
