FROM python:3.8.12-alpine3.14

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apk add --update --no-cache \
    gcc \
    musl-dev \
    postgresql-dev \
    python3-dev

WORKDIR /app

# Force copy, even when this file is already mounted.
# it forces a new layer creation, when changes in file are written.
COPY requirements.txt .
RUN pip install -r requirements.txt
